---
deployment:
 tasks:
 - export DEPLOYPATH=/home/tnhlabsc/django-advertools/
 - /bin/cp -R django_advertools $DEPLOYPATH
 - /bin/cp -R analyse $DEPLOYPATH
 - /bin/cp -R generateAds $DEPLOYPATH
 - /bin/cp -R api $DEPLOYPATH
 - /bin/cp -R media $DEPLOYPATH
 - /bin/cp -R logs $DEPLOYPATH
 - /bin/cp -R output $DEPLOYPATH
 - /bin/cp -R seo $DEPLOYPATH
 - /bin/cp -R static $DEPLOYPATH
 - /bin/cp -R templates $DEPLOYPATH
 - /bin/cp manage.py $DEPLOYPATH
 - /bin/cp requirements.txt $DEPLOYPATH